# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain_messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='blockchain_messages.proto',
  package='blockchain',
  syntax='proto3',
  serialized_pb=_b('\n\x19\x62lockchain_messages.proto\x12\nblockchain\"\xc9\x01\n\x0c\x43hainMessage\x1a\x1f\n\nAddMessage\x12\x11\n\tlast_hash\x18\x01 \x01(\t\x1ah\n\x0c\x45ntryMessage\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x11\n\trecipient\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x05\"%\n\tEntryType\x12\n\n\x06REWARD\x10\x00\x12\x0c\n\x08TRANSFER\x10\x01\".\n\x0bMessageType\x12\x0b\n\x07\x43ONFIRM\x10\x00\x12\x07\n\x03\x41\x44\x44\x10\x01\x12\t\n\x05\x45NTRY\x10\x02\x62\x06proto3')
)



_CHAINMESSAGE_ENTRYMESSAGE_ENTRYTYPE = _descriptor.EnumDescriptor(
  name='EntryType',
  full_name='blockchain.ChainMessage.EntryMessage.EntryType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REWARD', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRANSFER', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=158,
  serialized_end=195,
)
_sym_db.RegisterEnumDescriptor(_CHAINMESSAGE_ENTRYMESSAGE_ENTRYTYPE)

_CHAINMESSAGE_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='blockchain.ChainMessage.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONFIRM', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADD', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENTRY', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=197,
  serialized_end=243,
)
_sym_db.RegisterEnumDescriptor(_CHAINMESSAGE_MESSAGETYPE)


_CHAINMESSAGE_ADDMESSAGE = _descriptor.Descriptor(
  name='AddMessage',
  full_name='blockchain.ChainMessage.AddMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='last_hash', full_name='blockchain.ChainMessage.AddMessage.last_hash', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=89,
)

_CHAINMESSAGE_ENTRYMESSAGE = _descriptor.Descriptor(
  name='EntryMessage',
  full_name='blockchain.ChainMessage.EntryMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='blockchain.ChainMessage.EntryMessage.sender', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recipient', full_name='blockchain.ChainMessage.EntryMessage.recipient', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='blockchain.ChainMessage.EntryMessage.amount', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CHAINMESSAGE_ENTRYMESSAGE_ENTRYTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=195,
)

_CHAINMESSAGE = _descriptor.Descriptor(
  name='ChainMessage',
  full_name='blockchain.ChainMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_CHAINMESSAGE_ADDMESSAGE, _CHAINMESSAGE_ENTRYMESSAGE, ],
  enum_types=[
    _CHAINMESSAGE_MESSAGETYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=243,
)

_CHAINMESSAGE_ADDMESSAGE.containing_type = _CHAINMESSAGE
_CHAINMESSAGE_ENTRYMESSAGE.containing_type = _CHAINMESSAGE
_CHAINMESSAGE_ENTRYMESSAGE_ENTRYTYPE.containing_type = _CHAINMESSAGE_ENTRYMESSAGE
_CHAINMESSAGE_MESSAGETYPE.containing_type = _CHAINMESSAGE
DESCRIPTOR.message_types_by_name['ChainMessage'] = _CHAINMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChainMessage = _reflection.GeneratedProtocolMessageType('ChainMessage', (_message.Message,), dict(

  AddMessage = _reflection.GeneratedProtocolMessageType('AddMessage', (_message.Message,), dict(
    DESCRIPTOR = _CHAINMESSAGE_ADDMESSAGE,
    __module__ = 'blockchain_messages_pb2'
    # @@protoc_insertion_point(class_scope:blockchain.ChainMessage.AddMessage)
    ))
  ,

  EntryMessage = _reflection.GeneratedProtocolMessageType('EntryMessage', (_message.Message,), dict(
    DESCRIPTOR = _CHAINMESSAGE_ENTRYMESSAGE,
    __module__ = 'blockchain_messages_pb2'
    # @@protoc_insertion_point(class_scope:blockchain.ChainMessage.EntryMessage)
    ))
  ,
  DESCRIPTOR = _CHAINMESSAGE,
  __module__ = 'blockchain_messages_pb2'
  # @@protoc_insertion_point(class_scope:blockchain.ChainMessage)
  ))
_sym_db.RegisterMessage(ChainMessage)
_sym_db.RegisterMessage(ChainMessage.AddMessage)
_sym_db.RegisterMessage(ChainMessage.EntryMessage)


# @@protoc_insertion_point(module_scope)
